apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devops-test
  name: devops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devops-test
    spec:
      containers:
      - image: gcr.io/psyched-ceiling-286818/23people-devops-test:latest
        name: 23people-devops-test
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-test
  name: devops-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: devops-test
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devops-test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: devops-test
          servicePort: 8080
