steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG}", "${_DOCKERFILE}"]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG}"]
  # deploy container image to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: ["apply", "-f", "${_DOCKERFILE}deployments/k8s/"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=_${LOCATION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  # update gke image
- name: 'gcr.io/cloud-builders/kubectl'
  args: ["set", "image", "deployment", "${_IMAGE_NAME}2, "{_IMAGE_NAME}=gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_TAG}"]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=_${LOCATION}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

