steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${TAG}", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/${PROJECT_ID}/${IMAGE_NAME}:${TAG}"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=kubernetes-config-file
  - --image=gcr.io/project-id/image:tag
  - --location=${LOCATION}
  - --cluster=${CLUSTER_NAME}
